# Generated by Django 4.2.3 on 2023-07-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
