# Generated by Django 4.2.1 on 2023-07-10 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountdetails',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
