# Generated by Django 4.2.1 on 2023-07-10 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0002_customeraccountdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccountdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customeraccountdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='customeraccountdetails',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
