# Generated by Django 4.2.1 on 2023-07-14 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0002_remove_addnewrestaurant_id_addnewrestaurant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewRestaurantV2',
            fields=[
                ('id_Restaurant', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('bannar_img', models.ImageField(upload_to='banners/')),
                ('description', models.TextField()),
                ('time_for_delivery', models.PositiveIntegerField()),
                ('price_Max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_Min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AddNewRestaurant',
        ),
    ]
