# Generated by Django 4.2.1 on 2023-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0003_remove_customeraccountdetails_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='imgs/restaurant_logos/')),
                ('bannar_img', models.ImageField(upload_to='imgs/restaurant_bannar_img/')),
                ('description', models.TextField()),
                ('time_for_delivery', models.PositiveIntegerField()),
                ('price_Range', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
    ]
