# Generated by Django 4.2.1 on 2023-07-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0004_addrestaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrestaurant',
            old_name='price_Range',
            new_name='price_Max',
        ),
        migrations.AddField(
            model_name='addrestaurant',
            name='price_Min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
