# Generated by Django 4.2.1 on 2023-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0004_alter_addnewrestaurantv2_bannar_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewrestaurantv2',
            name='bannar_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
