# Generated by Django 4.2.1 on 2023-07-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0005_alter_addnewrestaurantv2_bannar_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='testImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testImg', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
