# Generated by Django 4.2.3 on 2023-07-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAuthorization', '0005_rename_price_range_addrestaurant_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrestaurant',
            name='bannar_img',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='addrestaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
